name: cp949
# SYNC: with README#Installation
# SYNC: with CHANGELOG
version: 1.2.1
description: CP949 Encoder/Decoder
environment:
  # SYNC: with CI config when sdk support range is changed.
  sdk: ">=2.1.1 <3.0.0"
homepage: https://github.com/jjangga0214/dart-cp949
repository: https://github.com/jjangga0214/dart-cp949
issue_tracker: https://github.com/jjangga0214/dart-cp949/issues
documentation: https://github.com/jjangga0214/dart-cp949
dev_dependencies:
  # package:test v1.5.3 support sdk v2.1.0, and CI uses sdk v2.1.1 as a lower compatibility boundary
  test: ">=1.5.3 <2.0.0"
